/**
 * Injection tokens for Dependency Injection
 */
export const TOKENS = {
  // Repositories
  PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  CART_REPOSITORY: 'CART_REPOSITORY',
  AUTH_REPOSITORY: 'AUTH_REPOSITORY', // If applicable

  // Services
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  ORDER_SERVICE: 'ORDER_SERVICE',
  CART_SERVICE: 'CART_SERVICE',
  AUTH_SERVICE: 'AUTH_SERVICE',
  LOGGER_SERVICE: 'LOGGER_SERVICE',
  CONFIG_SERVICE: 'CONFIG_SERVICE',
  REQUEST_CONTEXT: 'REQUEST_CONTEXT',

  // Providers
  LOGGER: 'LOGGER',
  APP_CONFIG: 'APP_CONFIG',
  DB_CONNECTION: 'DB_CONNECTION',
} as const;
